#!/usr/bin/env python

from common import *

srcdir  = "."
blddir = "build"


def set_options(opt):
  add_variant_options(opt)


def configure(conf):
  # Python.
  conf.check_tool("python")
  conf.check_python_version(minver=(2, 6))

  # C++.
  conf.check_tool("g++")
  set_orbit(conf)

  # Creating "debug" and "release" variants.
  create_variant(conf)


def build(bld):
  bld.recurse("server")
  check_variant(bld)
